name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/kaalimitti/kaalimitti_complete/kaalimiti
            git pull origin main
            cd backend
            npm install --production
            cd ../fronted
            npm install
            npm run build
            cd ..
            pm2 restart kaalimitti-backend
            echo "Deployment complete!"
